namespace PXE.Core.Enums
{
    public enum IncrementalValueType
    {
        None,
        Numbered, // Simple numerical increment: 1, 2, 3, ...
        Alphabetically, // Alphabetical increment: A, B, C, ...
        DateTimeStamp, // Timestamp: 20230101, 20230102, ...
        RomanNumerals, // I, II, III, IV, ...
        Hexadecimal, // Hex numbers: 1, 2, ... F, 10, 11, ...
        UniqueID, // UUIDs or GUIDs for uniqueness without a visible sequence
        CustomPattern // For user-defined sequences or patterns
    }
}